# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fib_gen(limit):
	fibs = [1,1]
	i = 1
	fib_term = 0
	while 1 > 0:
		fib_term = fibs[i] + fibs[i-1]
		if fib_term > limit:
			return fibs
		fibs.append(fib_term)
		i += 1
		
def sum_even_elements(array_to_sum):
	running_sum = 0
	for element in array_to_sum:
		if element % 2 == 0:
			running_sum += element
	return running_sum

print sum_even_elements(fib_gen(4000000))